"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then 
add one more letter at a random position.

Find the letter that was added in t.
"""

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        nums = [ord(ch) for ch in s + t]
        res = 0
        for num in nums:
            res ^= num

        return chr(res)
